import { RendererType } from '@/enums';
import { getExpressionsPlugin } from '@/utils/getterSetter';
import AudioController from '@/utils/audio/AudioController';
import ProjectInterface from '@/utils/helpers/ProjectInterface';
import type { AnimationConfiguration, AnimationData, AnimationDirection, AnimationEventName, AssetHandler, DocumentData, LottieAsset, MarkerData, Vector2 } from '@/types';
export default class AnimationItem {
    constructor();
    addEventListener: (event: AnimationEventName, callback: (e: Event) => void) => void;
    removeEventListener: (event: AnimationEventName, callback: (e: Event) => void) => void;
    triggerEvent: (event: AnimationEventName, arg?: unknown) => void;
    private _cbs;
    name: string;
    path: string;
    isLoaded: boolean;
    currentFrame: number;
    currentRawFrame: number;
    firstFrame: number;
    totalFrames: number;
    frameRate: number;
    frameMult: number;
    playSpeed: number;
    playDirection: AnimationDirection;
    playCount: number;
    animationData: Partial<AnimationData>;
    assets: LottieAsset[];
    isPaused: boolean;
    autoplay: boolean;
    loop: boolean | number;
    renderer: any;
    animationID: string;
    assetsPath: string;
    timeCompleted: number;
    segmentPos: number;
    isSubframeEnabled: boolean;
    segments: Vector2[];
    private _idle;
    private _completedLoop;
    projectInterface: null | ReturnType<typeof ProjectInterface>;
    imagePreloader: null | AssetHandler;
    audioController: AudioController;
    markers: MarkerData[];
    drawnFrameEvent: {
        currentTime: number;
        totalTime: number;
        direction: AnimationDirection;
    };
    expressionsPlugin: ReturnType<typeof getExpressionsPlugin>;
    frameModifier: AnimationDirection;
    onError?: (arg: unknown) => void;
    protected wrapper: HTMLElement | null;
    protected animType?: RendererType;
    protected fileName?: string;
    protected initialSegment?: Vector2;
    protected autoloadSegments: boolean;
    protected onEnterFrame: null | ((arg: unknown) => void);
    protected onLoopComplete: null | ((arg: unknown) => void);
    protected onComplete: null | ((arg: unknown) => void);
    protected onSegmentStart: null | ((arg: unknown) => void);
    protected onDestroy: null | ((arg: unknown) => void);
    setParams(params: AnimationConfiguration): void;
    onSetupError(): void;
    setupAnimation(data: AnimationData): void;
    setData(wrapper: HTMLElement, animationDatFromProps?: AnimationData): void;
    includeLayers(data: AnimationData): void;
    onSegmentComplete(data: AnimationData): void;
    loadNextSegment(): void;
    loadSegments(): void;
    imagesLoaded(): void;
    preloadImages(): void;
    configAnimation(animData: AnimationData): void;
    waitForFontsLoaded(): void;
    checkLoaded(): void;
    resize(width?: number, height?: number): void;
    setSubframe(flag: boolean): void;
    gotoFrame(): void;
    renderFrame(): void;
    play(name?: string): void;
    pause(name?: string): void;
    togglePause(name?: string): void;
    stop(name?: string): void;
    getMarkerData(markerName: number): MarkerData | null;
    goToAndStop(value: number, isFrame?: boolean, name?: string): void;
    goToAndPlay(value: number, isFrame?: boolean, name?: string): void;
    advanceTime(value: number): void;
    adjustSegment(arr: Vector2, offset: number): void;
    setSegment(init: number, end: number): void;
    playSegments(arr: Vector2 | Vector2[], forceFlag?: boolean): void;
    resetSegments(forceFlag?: boolean): void;
    checkSegments(offset: number): boolean;
    destroy(name?: string): void;
    setCurrentRawFrameValue(value: number): void;
    setSpeed(val: number, name?: string): void;
    setDirection(val: AnimationDirection, name?: string): void;
    setLoop(isLooping: boolean): void;
    setVolume(val: number, name?: string): void;
    getVolume(): number;
    mute(name?: string): void;
    unmute(name?: string): void;
    updaFrameModifier(): void;
    getPath(): string;
    getAssetsPath(assetData: LottieAsset): string;
    getAssetData(id: string): LottieAsset | null;
    hide(): void;
    show(): void;
    getDuration(isFrame?: boolean): number;
    updateDocumentData(path: string, documentData: DocumentData, index: number): void;
    trigger(name: AnimationEventName): void;
    triggerRenderFrameError(nativeError: unknown): void;
    triggerConfigError(nativeError: unknown): void;
}
